name: Joel Fernandes
description: Linux Kernel Engineer at NVIDIA
url: "http://joelfernandes.org"
baseurl: ""

permalink: /blog/:year-:month-:day/:title.html

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _reference

# Disqus comments
disqus_short_name: linuxinternals1
